-- Preserve identity uncertainty and byte-exact input provenance during phase 3.
ALTER TABLE articles ADD COLUMN identity_state TEXT NOT NULL DEFAULT 'identified' CHECK(identity_state IN ('identified','held','needs_review'));
CREATE TABLE migration_source_files(path TEXT PRIMARY KEY NOT NULL, migration_run_id TEXT NOT NULL REFERENCES migration_runs(id), sha256 TEXT NOT NULL, size INTEGER NOT NULL CHECK(size>=0), content BLOB NOT NULL, state TEXT NOT NULL CHECK(state IN ('imported','held')), reason TEXT);
CREATE TABLE article_source_provenance(source_record_id TEXT PRIMARY KEY NOT NULL REFERENCES source_records(id), article_id TEXT NOT NULL REFERENCES articles(id), source_table TEXT, source_row_id TEXT NOT NULL, old_article_key TEXT, original_url TEXT, input_hash TEXT NOT NULL, stored_content_hash TEXT, fetch_status TEXT);
CREATE TABLE article_identity_assessments(source_record_id TEXT PRIMARY KEY NOT NULL REFERENCES source_records(id), article_id TEXT NOT NULL REFERENCES articles(id), strategy TEXT NOT NULL CHECK(strategy IN ('legacy_key','corroborated','held')), reason TEXT NOT NULL, candidates_json TEXT NOT NULL CHECK(json_valid(candidates_json)), checks_json TEXT NOT NULL CHECK(json_valid(checks_json)));
CREATE TABLE legacy_history_records(id TEXT PRIMARY KEY NOT NULL, source_record_id TEXT NOT NULL REFERENCES source_records(id), kind TEXT NOT NULL, article_id TEXT REFERENCES articles(id), talent_id TEXT REFERENCES talents(id), raw_json TEXT NOT NULL CHECK(json_valid(raw_json)));
CREATE TABLE content_runtime_state(id TEXT PRIMARY KEY NOT NULL, source_record_id TEXT NOT NULL REFERENCES source_records(id), state_key TEXT NOT NULL, state_json TEXT NOT NULL CHECK(json_valid(state_json)));
CREATE TABLE review_entity_facts(entity_id TEXT NOT NULL REFERENCES review_entities(id), fact_id TEXT NOT NULL REFERENCES review_facts(id), PRIMARY KEY(entity_id,fact_id));
CREATE TABLE review_input_snapshots(review_id TEXT PRIMARY KEY NOT NULL REFERENCES review_records(id), input_hash TEXT NOT NULL, article_json TEXT NOT NULL CHECK(json_valid(article_json)), capture_json TEXT NOT NULL CHECK(json_valid(capture_json)));
CREATE TRIGGER immutable_legacy_history_id BEFORE UPDATE OF id ON legacy_history_records WHEN NEW.id!=OLD.id BEGIN SELECT RAISE(ABORT,'immutable id'); END;
CREATE TRIGGER immutable_runtime_id BEFORE UPDATE OF id ON content_runtime_state WHEN NEW.id!=OLD.id BEGIN SELECT RAISE(ABORT,'immutable id'); END;
