-- Initial identity assessments remain the adopted compatibility view.
-- Evaluations never adopt a new identity or release a hold.
CREATE TABLE identity_implementation_blobs(sha256 TEXT PRIMARY KEY NOT NULL, size INTEGER NOT NULL CHECK(size>=0), content TEXT NOT NULL);
CREATE TABLE identity_processors(id TEXT PRIMARY KEY NOT NULL, version TEXT NOT NULL, implementation_path TEXT NOT NULL, implementation_sha256 TEXT NOT NULL REFERENCES identity_implementation_blobs(sha256), rules_hash TEXT NOT NULL, manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)));
CREATE TABLE identity_processor_files(processor_id TEXT NOT NULL REFERENCES identity_processors(id), path TEXT NOT NULL, sha256 TEXT NOT NULL REFERENCES identity_implementation_blobs(sha256), PRIMARY KEY(processor_id,path));
CREATE TABLE identity_evidence_sets(id TEXT PRIMARY KEY NOT NULL, processor_id TEXT NOT NULL REFERENCES identity_processors(id), scope_json TEXT NOT NULL CHECK(json_valid(scope_json)), members_hash TEXT NOT NULL);
CREATE TABLE identity_evidence_members(evidence_set_id TEXT NOT NULL REFERENCES identity_evidence_sets(id), role TEXT NOT NULL CHECK(role IN ('article','subject','cache')), position TEXT NOT NULL, source_record_id TEXT NOT NULL REFERENCES source_records(id), input_hash TEXT NOT NULL, PRIMARY KEY(evidence_set_id,role,position));
CREATE INDEX identity_evidence_source ON identity_evidence_members(source_record_id);
CREATE TABLE identity_assessment_versions(id TEXT PRIMARY KEY NOT NULL, source_record_id TEXT NOT NULL REFERENCES source_records(id), input_hash TEXT NOT NULL, evidence_set_id TEXT NOT NULL REFERENCES identity_evidence_sets(id), evaluated_article_id TEXT NOT NULL, article_id TEXT NOT NULL REFERENCES articles(id), strategy TEXT NOT NULL CHECK(strategy IN ('legacy_key','corroborated','held')), reason TEXT NOT NULL, candidates_json TEXT NOT NULL CHECK(json_valid(candidates_json)), checks_json TEXT NOT NULL CHECK(json_valid(checks_json)), kind TEXT NOT NULL CHECK(kind IN ('initial','reevaluation')), UNIQUE(source_record_id,input_hash,evidence_set_id));
CREATE TABLE identity_assessment_events(id TEXT PRIMARY KEY NOT NULL, assessment_id TEXT NOT NULL REFERENCES identity_assessment_versions(id), business_id TEXT NOT NULL, recorded_at TEXT NOT NULL, lineage_json TEXT NOT NULL CHECK(json_valid(lineage_json)));
CREATE TRIGGER immutable_article_identity_assessments_update BEFORE UPDATE ON article_identity_assessments BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_article_identity_assessments_delete BEFORE DELETE ON article_identity_assessments BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_implementation_blobs_update BEFORE UPDATE ON identity_implementation_blobs BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_implementation_blobs_delete BEFORE DELETE ON identity_implementation_blobs BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_processors_update BEFORE UPDATE ON identity_processors BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_processors_delete BEFORE DELETE ON identity_processors BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_processor_files_update BEFORE UPDATE ON identity_processor_files BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_processor_files_delete BEFORE DELETE ON identity_processor_files BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_evidence_sets_update BEFORE UPDATE ON identity_evidence_sets BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_evidence_sets_delete BEFORE DELETE ON identity_evidence_sets BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_evidence_members_update BEFORE UPDATE ON identity_evidence_members BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_evidence_members_delete BEFORE DELETE ON identity_evidence_members BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_assessment_versions_update BEFORE UPDATE ON identity_assessment_versions BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_assessment_versions_delete BEFORE DELETE ON identity_assessment_versions BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_assessment_events_update BEFORE UPDATE ON identity_assessment_events BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER immutable_identity_assessment_events_delete BEFORE DELETE ON identity_assessment_events BEGIN SELECT RAISE(ABORT,'immutable identity evidence or assessment'); END;
CREATE TRIGGER identity_source_preserve_update BEFORE UPDATE ON source_records WHEN EXISTS(SELECT 1 FROM identity_evidence_members WHERE source_record_id=OLD.id) OR EXISTS(SELECT 1 FROM identity_assessment_versions WHERE source_record_id=OLD.id) BEGIN SELECT RAISE(ABORT,'immutable identity source evidence'); END;
CREATE TRIGGER identity_source_preserve_delete BEFORE DELETE ON source_records WHEN EXISTS(SELECT 1 FROM identity_evidence_members WHERE source_record_id=OLD.id) OR EXISTS(SELECT 1 FROM identity_assessment_versions WHERE source_record_id=OLD.id) BEGIN SELECT RAISE(ABORT,'immutable identity source evidence'); END;
